---
- name: Add NGINX Ingress Helm repository
  become: true
  become_user: jenkins
  command: >
    helm repo add ingress-nginx
    https://kubernetes.github.io/ingress-nginx
  register: helm_repo
  changed_when: "'already exists' not in helm_repo.stderr"
  failed_when: false

- name: Update Helm repositories
  become: true
  become_user: jenkins
  command: helm repo update

- name: Install NGINX Ingress Controller
  become: true
  become_user: jenkins
  command: >
    helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx
    --namespace ingress-nginx
    --create-namespace
    --wait
