grafana:
  enabled: false

alertmanager:
  enabled: true

prometheus:
  service:
    type: NodePort
    nodePort: 30909

  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true
