---
- name: Deploy Observability Stack
  hosts: jenkins
  become: yes

  roles:
    - { role: openebs, tags: ["openebs"] }
    - { role: otel-collector, tags: ["otel"] }
    - { role: jaeger, tags: ["jaeger"] }
    - { role: prometheus, tags: ["prometheus"] }
    - { role: servicemonitor, tags: ["servicemonitor"] }
    - { role: grafana, tags: ["grafana"] }
    - { role: elasticsearch, tags: ["elasticsearch"] }
    - { role: kibana, tags: ["kibana"] }
    - { role: fluent-bit, tags: ["fluent-bit"] } 
